### ISSUE TITLE
No CORS Configuration in Statseeker 5.2

### ISSUE THREAD

**Issue by jenner** [statseeker/grafana-statseeker-datasource#1]
I tried to follow the install instructions and it worked quite well, the only thing that didn't is the connection test in Grafana: I can't set the CORS include line because there is no "CORS Configuration" menu entry in "Statseeker Administration tool" -> "Statseeker Administration"... any hints?

**Comment by statseeker** [comment]
One of the pre-requisites is to have Statseeker 5.2.0 installed, please can you confirm that this is the case. You will be able to confirm the installed version of Statseeker on the NIM console at the bottom left hand side.

If you have any additional issues around your Statseeker install for 5.2.0 , please can you log a support call at the below URL

https://statseeker.com/customer-contact/support-request/

Kind Regards
Statseeker

**Comment by mrburns414** [comment]
I have statseeker 5.2 as well but still don't have a CORS Configuration area

**Comment by statseeker** [comment]
Please can you log a support call using the below URL as you should have a configuration item in the Administration Tool for the CORS Configuration in the "Statseeker Administration" section of the Admin tool if your version is 5.2.0 and higher.

https://statseeker.com/customer-contact/support-request/

Kind Regards
Statseeker
